apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.25.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-container
      restartPolicy: Always
      volumes:
        - name: mongodb-data-container
          persistentVolumeClaim:
            claimName: mongodb-data-container
status: {}
