apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: service-api
    spec:
      containers:
        - args:
            - rerun
            - "--background"
            - ruby
            - service.rb
          image: thenice/domain:latest
          name: service-api
          ports:
            - containerPort: 4567
          resources: {}
      restartPolicy: Always
status: {}
