apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  type: LoadBalancer
  ports:
    - name: "service-api"
      port: 4567
      targetPort: 4567
  selector:
    io.kompose.service: service-api
status:
  loadBalancer: {}
