apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: service-api
    spec:
      containers:
        - args:
            - ruby
            - service.rb
            - "-o"
            - "0.0.0.0"
            - "-p"
            - "4567"
          image: thenice/domain:latest
          name: service-api
          ports:
            - containerPort: 4567
          resources: {}
      restartPolicy: Always
status: {}
