apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.25.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  type: LoadBalancer
  ports:
    - name: "service-api"
      port: 4567
      targetPort: 4567
  selector:
    io.kompose.service: service-api
status:
  loadBalancer: {}
