apiVersion: v1
kind: Service
metadata:
  name: domain
  labels:
    app: domain
spec:
  clusterIP: None
  selector:
    app: domain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain
  labels:
    app: domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain
  template:
    metadata:
      labels:
        app: domain
    spec:
      containers:
      - name: domain
        image: domain
