name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: domain
      run: docker login --username thenice fae0058b-b6ea-4b72-a264-fbb6613a0ab2
      run: docker build . --file Dockerfile --tag domain:$(date +%s)
      run: docker push
